apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-deployment
  labels:
    app: nest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest
  template:
    metadata:
      labels:
        app: nest
    spec:
      containers:
        - name: nest-container-ready
          image: ammaralshari/streammix-backend:9519c4dd4b194e9e12b002bb97112919c3d10b51
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: mysql-secret
            - secretRef:
                name: auth-secret
            - configMapRef:
                name: mysql-config
          env:
            - name: ANGULAR_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: ANGULAR_URL
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "150Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: nest-service
spec:
  selector:
    app: nest
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
