apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-deployment
  labels:
    app: nest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest
  template:
    metadata:
      labels:
        app: nest
    spec:
      containers:
        - name: nest-container
          image: ammaralshari/streammix-backend:a4f3f8b377772392a7439b4c073589400ae36058
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: mysql-secret
            - secretRef:
                name: auth-secret
            - configMapRef:
                name: mysql-config
          env:
            - name: ANGULAR_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: ANGULAR_URL
---
apiVersion: v1
kind: Service
metadata:
  name: nest-service
spec:
  selector:
    app: nest
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
