name: Build and Upload Image to MinIO

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: "Docker image name"
        required: true
        default: "dockerfile"

      build_dir:
        description: "Dockerfile directory"
        required: true
        default: "."

      tar_name:
        description: "Saved TAR file name"
        required: true
        default: "docker-image"

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ inputs.image_name }}
      BUILD_DIR: ${{ inputs.build_dir }}
      TAR_NAME: ${{ inputs.tar_name }}

      MINIO_ENDPOINT: https://minio-api.bab-poc.sa.focal.mozn.sa
      MINIO_BUCKET: docker-images

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Build Docker image
        run: |
          docker build \
            -t $IMAGE_NAME:${{ github.sha }} \
            $BUILD_DIR


      - name: Save Docker image
        run: |
          docker save \
            $IMAGE_NAME:${{ github.sha }} \
            -o $TAR_NAME-${{ github.sha }}.tar

          ls -lh $TAR_NAME-${{ github.sha }}.tar


      - name: Install AWS CLI
        run: |
          curl -fsSL https://awscli.amazonaws.com/v2/install.sh | bash
          echo "$HOME/.local/bin" >> $GITHUB_PATH


      - name: Configure MinIO
        run: |
          aws configure set aws_access_key_id \
            "${{ secrets.MINIO_ACCESS_KEY_ID }}" \
            --profile minio

          aws configure set aws_secret_access_key \
            "${{ secrets.MINIO_SECRET_ACCESS_KEY }}" \
            --profile minio

          aws configure set region us-east-1 \
            --profile minio

          aws configure set s3.addressing_style path \
            --profile minio
            
          aws configure set s3.multipart_chunksize 512MB \
            --profile minio

          aws configure set s3.max_concurrent_requests 4 \
            --profile minio


      - name: Upload image to MinIO
        run: |
          aws s3 cp \
            $TAR_NAME-${{ github.sha }}.tar \
            s3://$MINIO_BUCKET/$TAR_NAME-${{ github.sha }}.tar \
            --endpoint-url "$MINIO_ENDPOINT" \
            --profile minio \
            --no-progress


      - name: Upload Summary
        run: |
          cat >> "$GITHUB_STEP_SUMMARY" <<EOF
          ### ✅ Image uploaded successfully
      
          - **Image:** \`$IMAGE_NAME:${{ github.sha }}\`
          - **TAR:** \`$TAR_NAME-${{ github.sha }}.tar\`
          - **MinIO:** \`s3://$MINIO_BUCKET/$TAR_NAME-${{ github.sha }}.tar\`
          EOF
